[tool.poetry]
name = "dspy-prompt-optimization"
version = "0.0.0"
description = "Dspy module to support both prompt optimization and build optimizer pipelines"
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "dspy_prompt_optimization", from = "." }
]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
pydantic = ">=2.10.5,<3.0.0"
langchain-openai = ">=0.2.14,<0.3.0"
setuptools = ">=75.8.0,<76.0.0"
python-dotenv = ">=1.0.1,<2.0.0"


[tool.poetry.scripts]
generate_data = "dspy_prompt_optimization.generate_dspy_data:main"
build_optimizer = "dspy_prompt_optimization.build_optimizer:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
