#!/usr/bin/env python3
import argparse
import json
import dspy
import dotenv
import dspy.evaluate
from dspy.evaluate import Evaluate
from dspy.teleprompt import MIPROv2

dotenv.load_dotenv()


###############################################
# 1. Parse command-line arguments
###############################################
def parse_args():
    parser = argparse.ArgumentParser(description="Optimize a ChainOfThought with MIPROv2 and evaluate it.")
    parser.add_argument("--data_path", type=str, required=True, 
                        help="Path to the JSON data file (e.g., data_for_dspy.json).")
    parser.add_argument("--output_path", type=str, required=True, 
                        help="Directory or filename prefix where the optimized model/program will be saved.")
    return parser.parse_args()

###############################################
# 2. Define the faithfulness signature & metric
###############################################
class CheckCitationFaithfulness(dspy.Signature):
    """
    Verify that the answer is based on the provided question.
    """
    question: str = dspy.InputField(desc="The question that the answer is based on")
    answer: str = dspy.InputField(desc="The answer generated by the model given the question")
    number_of_claims_that_can_be_inferrred: int = dspy.OutputField(desc="The number of claims in the answer that can be inferred from the question")
    total_number_of_claims: int = dspy.OutputField(desc="The total number of claims in the answer")

def evaluate_faithfulness(question: str, answer: str) -> float:
    """
    Defines a custom metric to check whether the answer is faithful
    to the question by counting how many claims can be inferred.
    """
    # Initialize the DSPy predictor with the defined signature
    faithfulness_checker = dspy.ChainOfThought(CheckCitationFaithfulness)
    
    # Perform the faithfulness check
    result = faithfulness_checker(question=question, answer=answer)

    # Calculate the faithfulness score
    if result.total_number_of_claims > 0:
        return result.number_of_claims_that_can_be_inferrred / result.total_number_of_claims
    else:
        return 0.0

###############################################
# 3. Main routine
###############################################
def main():
    args = parse_args()

    # Configure the LM in DSPy
    lm = dspy.LM("openai/gpt-4")
    dspy.configure(lm=lm)

    # A basic ChainOfThought structure: "question -> answer"
    cot = dspy.ChainOfThought("question -> answer")

    # Load the data
    with open(args.data_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Build dataset
    dataset = []
    for d in data:
        # Combine fields from the JSON into a single "question" string, if desired
        question = (d["about_me"] + " " + d["context"] + " " + d["question"])
        answer = d["response"]
        dataset.append(dspy.Example(question=question, answer=answer).with_inputs("question"))

    # Create an evaluator for the dev/test set
    evaluate = Evaluate(
        devset=dataset,
        metric=evaluate_faithfulness,
        num_threads=8,
        display_progress=True,
        display_table=False,
        max_errors=len(dataset),
    )

    # Evaluate the unoptimized program (optional, but good for baseline)
    print("\n=== Baseline evaluation of original ChainOfThought ===")
    baseline_score = evaluate(cot)
    print(f"Baseline evaluation score: {baseline_score:.4f}\n")

    # Initialize the MIPROv2 optimizer
    teleprompter = MIPROv2(
        metric=evaluate_faithfulness,
        auto="heavy",  # can be 'light', 'medium', or 'heavy'
    )

    # Optimize the chain of thought
    print("=== Optimizing program with MIPROv2... ===")
    optimized_program = teleprompter.compile(
        cot.deepcopy(),
        trainset=dataset,
        max_bootstrapped_demos=3,
        max_labeled_demos=4,
        requires_permission_to_run=False,
    )
    # Save optimized program for future use
    optimized_program_path = args.output_path
    optimized_program.save(optimized_program_path)
    print(f"Optimized program saved to: {optimized_program_path}\n")

    # Evaluate the optimized program
    print("=== Evaluate optimized program on test set ===")
    optimized_score = evaluate(optimized_program, devset=dataset)
    print(f"Optimized program evaluation score: {optimized_score:.4f}\n")

    print("=== Done! ===")

if __name__ == "__main__":
    main()
